n = str(input('Digite seu nome completo: '))
print('Analisando...')
print(f'Seu nome em maiúsculo: {n.upper()}.')
print(f'Seu nome em minúscolo: {n.lower()}.')
print(f'Seu nome tem ao todo: {(len(n) - n.count(" "))} letras.')
separa = n.split()
print(f'Seu primeiro nome é {separa[0]} e ele tem {len(separa[0])} letras')
